version: '3'

services:
  node-app:
    build:
      context: Node
    container_name: node-app
    entrypoint: bash -c "npm install && dockerize -wait tcp://mysql-db:3306 -timeout 60s node index.js"
    networks:
      - nodeapp
    tty: true
    volumes:
      - ./Node:/usr/src/app
    depends_on:
      - mysql-db
  mysql-db:
    build:
      context: Mysql
    command: --innodb-use-native-aio=0
    container_name: mysql-db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./Mysql/volume:/var/lib/mysql
    networks:
      - nodeapp
  nginx-app:
      restart: always
      container_name: nginx-app
      build:
          context: ./Nginx
      ports:
          - "8080:80"
      networks:
        - nodeapp
      depends_on:
        - node-app
networks:
  nodeapp:
    driver: bridge
